# =============================
# ChainLit Configuration File
# =============================

# General settings
enable_telemetry = false

# Environment variables required from users (if any)
user_env = []

# Session handling
session_timeout = 3600                   # In seconds (1 hour)
user_session_timeout = 1296000          # In seconds (15 days)

# Caching
cache = false

# CORS settings
allow_origins = ["*"]

# =============================
# Feature Configuration
# =============================

[features]
unsafe_allow_html = false               # Prevents rendering raw HTML (security)
latex = false                           # Disable LaTeX rendering
user_message_autoscroll = true          # Scrolls to newest message automatically
auto_tag_thread = true                  # Tags threads with current chat profile
edit_message = true                     # Allow user to edit their message

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]                        # Allow all file types (you can restrict)
max_files = 20
max_size_mb = 500

[features.audio]
sample_rate = 24000

[features.mcp.sse]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = [ "npx", "uvx" ]

# =============================
# UI Customization
# =============================

[UI]
name = "Zomato Chatbot by Aydie"
logo_file_url = "https://aydie.in/assets/llm/zomato.png"                      # Path to your logo (or use full URL)
default_avatar_file_url = "https://aydie.in/assets/llm/avatar.png"          # Path to avatar image
cot = "full"
alert_style = "classic"

# Optional UI Settings (Uncomment if needed)
# default_theme = "dark"
# layout = "wide"
# default_sidebar_state = "open"
# description = "Your AI-powered food ordering assistant"
# custom_css = "/public/custom.css"
# custom_js = "/public/custom.js"
# custom_js_attributes = "async type = \"module\""
# login_page_image = "/public/login-bg.jpg"
# login_page_image_filter = "brightness-50 grayscale"
# custom_meta_image_url = "https://yourdomain.com/meta-banner.png"

# Optional links in the UI header
# [[UI.header_links]]
# name = "GitHub"
# display_name = "View Code"
# icon_url = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
# url = "https://github.com/aydiegithub/zomato-chatbot"

# =============================
# Meta Information
# =============================

[meta]
generated_by = "2.6.0"
